# Title: Subclass of Disjoint Classes
# Constraint Description: No class should be a subclass of two disjoint classes.
# Severity: Error

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?class ?disjoint1 ?disjoint2 ?error WHERE {
  ?class rdfs:subClassOf ?disjoint1, ?disjoint2 .
  ?disjoint1 owl:disjointWith ?disjoint2 .
  FILTER (?disjoint1 != ?disjoint2)
  BIND (concat("ERROR: Class ", str(?class), " is subclass of disjoint classes ", str(?disjoint1), " and ", str(?disjoint2)) AS ?error)
}
